version: '3.8'

services:
  koti-travel:
    image: koti-travel-app
    container_name: koit_travel
    ports:
      - "8080:9292"

  mysql:
    image: mysql:latest
    container_name: mysql_container
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: my-secret-pw
      MYSQL_DATABASE: mydatabase
      MYSQL_USER: myuser
      MYSQL_PASSWORD: mypassword
    volumes:
      - ./mysql_data:/var/lib/mysql

volumes:
  mysql_data:
